spring.application.name=ministore
spring.datasource.url=jdbc:postgresql://localhost:5432/ministore
spring.datasource.username=sadmin
spring.datasource.password=929292

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
